version: "3"
networks:
  web:
    external: true
  internal:
    external: false

services:
  spring-cropmanager:
    image: tsobu/spring-cropmanager:latest
    ports:
      - 8098:8098
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api.tsobu.geek"
      - traefik.docker.network=web
      - traefik.port=8098
    networks:
      - web
      - internal
  plumber-cropmanager:
    image: tsobu/plumber-cropmanager:latest
    ports:
      - 8000:8000
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:plumber.tsobu.geek"
      - traefik.docker.network=web
      - traefik.port=8000
    networks:
      - web
      - internal
  traefik:
    image: traefik:latest
    container_name: traefik
    labels:
      - "traefik.frontend.rule=Host:monitor.tsobu.geek"
      - traefik.port=8000
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/conf/traefik.toml:/traefik.toml
      - ${PWD}/conf/cropmanager.json:/cropmanager.json
