version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    #command: --api --docker  # Enables the web UI and tells Traefik to listen to docker
    restart: always
    ports:
      - 80:80
     # - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/conf/${CONFIG_FILE}:/traefik.toml
      - ${PWD}/conf/acme.json:/acme.json
    labels:
      - traefik.backend=monitor
      - traefik.frontend.rule=Host:monitor.${DOMAIN}
      - traefik.docker.network=web
      - traefik.port=${MONITOR_PORT}
    networks:
      - web

networks:
  internal:
    external: false
  web:
    external: true