#FROM wnameless/oracle-xe-11g
#FROM rodrigozc/oracle12c
#FROM lirina2006/oracle18
FROM oracle/database:12.2.0.1-ee

MAINTAINER Sammy Barasa <barsamms@gmail.com>
ADD init.sql /docker-entrypoint-initdb.d/
