version: '3'
services:
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
    depends_on:
      - spring-cropmanager
  spring-cropmanager:
    image: tsobu/spring-cropmanager:latest
    expose:
      - "8098"