version: '3.3'

services:
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${CROP_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${CROP_DATABASE}
      MYSQL_USER: ${CROP_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${CROP_DATABASE_PASSWORD}
    networks:
      - web
    restart: on-failure
    ports:
      - 3306:3306
    #volumes:
    #  - ${PWD}/mariadb:/var/lib/mysql
  akilimo-spring:
    container_name: akilimo-spring
    image: tsobu/spring-cropmanager:latest
    restart: always
    ports:
      - 8098:8098
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CROP_DATABASE_URL=${CROP_DATABASE_URL}
      - CROP_DATABASE_USERNAME=${CROP_DATABASE_USERNAME}
      - CROP_DATABASE_PASSWORD=${CROP_DATABASE_PASSWORD}
      - PLUMBER_ENDPOINT=${PLUMBER_ENDPOINT}
    depends_on:
      - db
    networks:
      - web
      - internal
  akilimo-r:
    container_name: akilimo-r
    #image: tsobu/plumber-cropmanager:release-2.0
    image: tsobu/plumber-cropmanager:latest
    restart: always
    ports:
      - 8000:8000
    #depends_on:
    #  - akilimo-db
    networks:
      - web
      - internal
networks:
  internal:
    external: false
  web:
    external: true
