version: '3.3'

services:
  rancher:
    container_name: rancher
    image: rancher/rancher:v2.2.4-rc20
    restart: on-failure
    ports:
      - 80:80
      - 443:443
#      - 8080:80
#      - 8443:443
    volumes:
      - /opt/rancher:/var/lib/rancher
      - ${R_ROOT}/akilimo_recommendation:${R_ROOT}/akilimo_recommendation
      - ${R_ROOT}/gisdata:${R_ROOT}/gisdata
      - ${R_ROOT}/currentyield:${R_ROOT}/currentyield
#    networks:
#      - web
#      - internal
#networks:
#  internal:
#    external: false
#  web:
#    external: true
